name: Build Android APK
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v3
        with: { gradle-version: "8.7" }
      - run: |
          gradle wrapper --gradle-version 8.7
          ./gradlew --version
      - run: ./gradlew :app:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
