name: Build Android APK

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # نیازی به chmod نیست چون هنوز gradlew وجود ندارد
      - name: Install Gradle (temporary) and generate wrapper
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7
          ./gradlew --version

      - name: Build APK (release)
        run: ./gradlew :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
